import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'

const poppins = Poppins({ subsets:['devanagari'],weight:"500" })

export const metadata: Metadata = {
  title: 'zz',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
      <div>
        <p>dsds</p>
      </div>
    </html>
  )
}
